SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;

ALTER TABLE operational_status_types CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE operational_status_types ADD COLUMN emoji VARCHAR(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ALTER TABLE operational_status_types ADD COLUMN discordem VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

SET FOREIGN_KEY_CHECKS=1;
